### ISSUE TITLE
RHEL7 supporrt

### ISSUE THREAD

**Issue by ubellavance** [jhoblitt/puppet-awstats#9]
Hi,

I've started using your module with RHEL and it works (I have edited params.pp to make it work with 7). I havent' used your module before but I can say that we must set the DirIcons setting to `"/awstatsicons"` to make it match the value in `/etc/httpd/conf.d/awstats.conf` file provided by the EPEL rpm.

I currently have tested only a subset of all the available settings:

- LogFile
- LogFormat
- SiteDomain
- HostAliases
- DirIcons

I'll test more in the next weeks, but is there something that you'd like me to test for EL7?

**Comment by jhoblitt** [comment]
Does the EPEL7 package have a systemd service file?

**Comment by ubellavance** [comment]
Why would it have a service file? It's not a service... It runs as a cron job. I checked with rpm -ql and it looks like there is no service file.

**Comment by jhoblitt** [comment]
It sounds like there shouldn't be any gotchas to adding EL7 support.

**Comment by jhoblitt** [comment]
A module should have reasonable defaults for any platform is claims to support.

**Comment by tmannerm** [comment]
Even since PR #7, isn't this done? A forge release would be nice too, though..

**Comment by jhoblitt** [comment]
Resolved by #7
